---
title: "practise_hw2"
output: html_document
date: "2024-10-02"
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

# Load the dataset
```{r}
library (dplyr)
data <- read.table("https://www.dipintothereef.com/uploads/3/7/3/5/37359245/rairuoho.txt", header = TRUE, stringsAsFactors = FALSE)

str(data)
```

# Replace "nutrient" with "enriched" in the treatment variable
```{r eval = FALSE}

data$treatment <- gsub("nutrient", "enriched", data$treatment)
```
# Reshape the data into long format to create a single 'day' variable
```{r eval = FALSE}
data_long <- data %>%
  pivot_longer(cols = starts_with("day"), 
               names_to = "day", 
               values_to = "length")
```

# Combine Spatial1 and Spatial2 into a new column called 'upper_left'
```{r eval = FALSE}
data_long <- data_long %>%
  mutate(upper_left = paste(spatial1, spatial2, sep = "_"))
```

# Remove the row, column, Spatial1, and Spatial2 columns
```{r eval = FALSE}
data_long <- data_long %>%
  select(-c(row, column, spatial1, spatial2))
```

# Convert 'day' into a factor with the correct levels. Create csv
```{r eval = FALSE}
data_long$day <- factor(data_long$day, levels = c("day3", "day4", "day5", "day6", "day7", "day8"))

head(data_long)

write.csv(data_long, "cleaned_data.csv", row.names = FALSE)
```




